CALL osae_sp_object_type_add ('DSC Alarm','DSC Alarm Panel','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','DSC Alarm');
CALL osae_sp_object_type_state_add ('OFF','Stopped','DSC Alarm');
CALL osae_sp_object_type_property_add ('SoftwareVersion','String','','DSC Alarm',0);
CALL osae_sp_object_type_property_add ('Baud','Integer','9600','DSC Alarm',0);
CALL osae_sp_object_type_property_add ('UpdateTime','Integer','60','DSC Alarm',0);
CALL osae_sp_object_type_property_add ('Code','Integer','0','DSC Alarm',0);
CALL osae_sp_object_type_property_add ('Password','String','','DSC ALARM',0);
CALL osae_sp_object_type_property_add ('Ethernet','Boolean','','DSC ALARM',0);
CALL osae_sp_object_type_property_add ('Keybus','String','','DSC Alarm',0);
CALL osae_sp_object_type_event_add ('ON','Started','DSC Alarm');
CALL osae_sp_object_type_event_add ('OFF','Stopped','DSC Alarm');

CALL osae_sp_object_type_add ('DSC ALARM PARTITION1','DSC Alarm Patition 1','','',1,0,0,1);
CALL osae_sp_object_type_property_add ('Status','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone01','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone02','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone03','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone04','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone05','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone06','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone07','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone08','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone09','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone10','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone11','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone12','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone13','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone14','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone15','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('Zone16','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('TroubleLED','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Ready','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Armed','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Memory','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Bypass','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Trouble','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Program','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Fire','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED Backlight','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_property_add ('LED AC','String','','DSC ALARM PARTITION1',0);
CALL osae_sp_object_type_event_add ('INALARM','Partition In Alarm','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ARMED','Partition Armed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('EXITDELAYINPROGRESS','Partition Exit Delay In Progress','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ENTRYDELAYINPROGRESS','Partition Entry Delay In Progress','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE01 OPEN','Zone 1 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE01 CLOSED','Zone 1 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE02 OPEN','Zone 2 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE02 CLOSED','Zone 2 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE03 OPEN','Zone 3 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE03 CLOSED','Zone 3 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE04 OPEN','Zone 4 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE04 CLOSED','Zone 4 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE05 OPEN','Zone 5 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE05 CLOSED','Zone 5 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE06 OPEN','Zone 6 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE06 CLOSED','Zone 6 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE07 OPEN','Zone 7 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE07 CLOSED','Zone 7 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE08 OPEN','Zone 8 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE08 CLOSED','Zone 8 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE09 OPEN','Zone 9 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE09 CLOSED','Zone 9 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE10 OPEN','Zone 10 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE10 CLOSED','Zone 10 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE11 OPEN','Zone 11 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE11 CLOSED','Zone 11 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE12 OPEN','Zone 12 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE12 CLOSED','Zone 12 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE13 OPEN','Zone 13 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE13 CLOSED','Zone 13 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE14 OPEN','Zone 14 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE14 CLOSED','Zone 14 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE15 OPEN','Zone 15 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE15 CLOSED','Zone 15 Closed','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE16 OPEN','Zone 16 Open','DSC ALARM PARTITION1');
CALL osae_sp_object_type_event_add ('ZONE16 CLOSED','Zone 16 Closed','DSC ALARM PARTITION1');

CALL osae_sp_object_type_add ('DSC ALARM PARTITIONX','DSC Alarm Patition X','','',1,0,0,1);
CALL osae_sp_object_type_property_add ('Status','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone01','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone02','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone03','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone04','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone05','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone06','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone07','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone08','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone09','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone10','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone11','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone12','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone13','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone14','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone15','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_property_add ('Zone16','String','','DSC ALARM PARTITIONX',0);
CALL osae_sp_object_type_event_add ('INALARM','Partition In Alarm','DSC ALARM PARTITIONX');
CALL osae_sp_object_type_event_add ('ARMED','Partition Armed','DSC ALARM PARTITIONX');
CALL osae_sp_object_type_event_add ('EXITDELAYINPROGRESS','Partition Exit Delay In Progress','DSC ALARM PARTITIONX');
CALL osae_sp_object_type_event_add ('ENTRYDELAYINPROGRESS','Partition Entry Delay In Progress','DSC ALARM PARTITIONX');
